#!/usr/bin/env bash
#Creating a script that displays Best School for 9 times and Hi for the 10th.

x=1
while [ $x -le 10 ]
do
    echo "Best School"
    if [ $x -eq 9 ]
    then
	echo "Hi"
    fi
    ((x++))
done
